### ISSUE TITLE
Can not resolve workspace folder

### ISSUE THREAD

**Issue by venturescode** [liximomo/vscode-remote-fs#16]
I have installed your extension, and I really enjoy it.

I have added the "User Settings" successfully and am able to browse our online SFTP site.

However, next to each Workspace folder, it has an "!" with the error "Can not resolve workspace folder" (highlighted in yellow).

Can you help me fix this error?

Thanks.

**Comment by liximomo** [comment]
It seem to be a problem of vscode. [vscode#50866](https://github.com/Microsoft/vscode/issues/50866)

**Comment by KamasamaK** [comment]
That upstream issue was resolved and included in v1.25

**Comment by danielmarg** [comment]
I have the same problem. It seems like a .git folder is causing the problem and is not shown.

**Comment by danielmarg** [comment]
One more thing. Code Spell Checker by Street Side Software is causing this issue for me. Still don't see my .git folder :/
